name: Combine JSON Files and Publish to gh-pages

on:
  push:
    paths:
      - 'submodules/lucy/**'
      - 'submodules/ariel/**'
      - 'submodules/**/**'
  schedule:
    - cron: '1/5 * * * *'  # Run every 5 minutes

jobs:
  combine-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true  # Ensure submodules are checked out
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: npm install

    - name: Ensure submodules are up-to-date
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive
        git submodule foreach --recursive 'git fetch origin && git checkout main'
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: python -m pip install --upgrade pip
    
    - name: Run combine script
      run: python src/data/combine_json.py
    
    - name: Show contents of pryzumData.json
      run: cat src/data/pryzumData.json

    - name: Verify combined data file existence
      run: |
        if [ -f "src/data/pryzumData.json" ]; then
          echo "pryzumData.json exists."
          ls -l src/data/pryzumData.json
        else
          echo "pryzumData.json does not exist."
          ls -l src/data
          exit 1
        fi
    
    - name: Stage changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add src/data/pryzumData.json
        git status
        git diff --cached --name-only

    - name: Check for changes
      id: check_changes
      run: |
        if git diff --cached --name-only | grep -q 'src/data/pryzumData.json'; then
          echo "changes_detected=true" >> $GITHUB_ENV
        else
          echo "changes_detected=false" >> $GITHUB_ENV
        fi

    - name: Commit and push changes
      if: env.changes_detected == 'true'
      run: |
        git commit -m 'Automated combine JSON files'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run predeploy and deploy scripts
      if: env.changes_detected == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm run predeploy
        npx gh-pages -d build -t $GITHUB_TOKEN

    - name: No changes detected
      if: env.changes_detected == 'false'
      run: echo "There are no updates."
